Update index.md
wirenboard/website pull request #33
Opened 2024-09-02 14:02 UTC by matveevrj

## Описание изменения

Убрал всю лирику про Долгопрудный и Физтех и захват мира.

## Чеклист ревью

Перед мержем не забудь проверить:

- [x] правописание в тексте, опечатки

Опционально (но важно для изменений в инфраструктуру):

- [ ] задеплоить на stage, чтобы проверить, что все работает

2024-09-03 07:57 UTC, aadegtyarev commented on content/en/jobs/index.md
> +Wiren Board was founded in 2013. The owners of the company are people who know how to do tough engineering things themselves, and there is a lot to learn from them. The company has a Western style of
>The company has a Western style of management.

Страница английская. Наверное, про западный стиль управления можно не писать, непонятно оно им будет.

2024-09-03 07:57 UTC, aadegtyarev commented on content/en/jobs/index.md
>  There are more than 20 people in our engineering team. The work can be roughly divided into three big directions:
>There are more than 30

Устарело. Напиши больше 30 и в русской версии тоже исправь.

2024-09-03 07:59 UTC, aadegtyarev commented
И веточки называть лучше по другому шаблону, например feature/MAR-648-edit-page-jobs. Сейчас менять не надо, на будущее.

2024-09-04 11:07 UTC, aadegtyarev commented
Что-то не так, почему две папки jobs?
![изображение](https://github.com/user-attachments/assets/f57c6400-8cf8-4522-a02a-c63ef9e479ac)

Локально тоже
![изображение](https://github.com/user-attachments/assets/786aec9f-436a-4a47-9f7d-3ca0bb0d1d69)

2024-09-13 07:39 UTC, aadegtyarev approved these changes
После правки ок.

2024-09-18 13:50 UTC, lostpoint-ru approved these changes

2024-09-20 07:46 UTC, aadegtyarev requested changes
Почему в вакансиях на английском сайте Россия?? Астана у нас там как минимум.

2024-09-20 07:46 UTC, aadegtyarev commented on content/en/jobs/_includes/CircuitEngineer.md
> +* spacious and comfortable office, with a tennis table and a massage chair, which is easy to get to: from the Novodachnaya platform (MCD-1) or by car along Dmitrovskoe highway.
Эээй, какая Россия тут я же исправил.

2024-09-20 07:50 UTC, aadegtyarev approved these changes
Оставляем мои правки, не вливай больше ничего.

2024-09-20 07:53 UTC, merged