SOFT-4525
wirenboard/website pull request #53
Opened 2024-10-23 14:17 UTC by ninedev-i

Добавил страницу с видео, компонент видео-галлерея и документацию подо все это.
![image](https://github.com/user-attachments/assets/672ede2c-7e18-4f29-bee3-0feb0ffe3eb4)

2024-10-24 13:56 UTC, aadegtyarev submitted a review, later dismissed
Оставил вопрос про картинку.

2024-10-24 13:56 UTC, aadegtyarev commented on doc/video.md
> +2. При необходимости добавьте в папку [public/img/video](/public/img/video) изображение в формате webp и шириной не больше 450px.
У нас где-то в соседних сущностях (например, внедрения) есть требование, что не более 500 px. Можно тут сделать так же? Чтобы размер обложек был везде одинаковый и меньше думать?

2024-10-24 15:05 UTC, ninedev-i commented on doc/video.md
> +2. При необходимости добавьте в папку [public/img/video](/public/img/video) изображение в формате webp и шириной не больше 450px.
Поправил

2024-10-24 15:26 UTC, aadegtyarev submitted a review, later dismissed

2024-10-25 05:00 UTC, KraPete requested changes

2024-10-25 10:25 UTC, ninedev-i commented on components/content/VideoGallery.vue
> +type Video = [string, string, string];
Это сделано для удобства редакторов. Приведу пример как это будут использовать они
сейчас:
`
:video-gallery{
    :data='[
        ["URL ролика без всего"],
        ["URL ролика c подписью и обложкой", "Подпись к ролику", "Обложка"],
        ["URL ролика без подписи", "", "Обложка"],
        ["URL ролика c подписью без обложки", "Подпись к ролику"]
    ]'
}
`
то как это предлагаешь ты:
`
:video-gallery{
    :data='[
        { url: "URL ролика без всего" },
        { url: "URL ролика c подписью и обложкой", title: "Подпись к ролику", cover: "Обложка" },
        { url: "URL ролика без подписи", cover: "Обложка" },
        { url: "URL ролика c подписью без обложки", title: "Подпись к ролику" }
    ]'
}
`

как будто первый вариант лаконичнее, плюс IDE не подскажет как заполнять. Но можем спросить @aadegtyarev

2024-10-25 11:26 UTC, KraPete commented on components/content/VideoGallery.vue
> +type Video = [string, string, string];
Тогда надо это к комментариях описать хотя бы. Потом забудется, что за массив из трёх строк

2024-10-25 14:59 UTC, ninedev-i commented on pages/contents/video.vue
> +        :data="data.sort((a, b) => filterDate === 'filter_asc' ? new Date(b.date) - new Date(a.date) : new Date(a.date) - new Date(b.date))
done

2024-10-25 14:59 UTC, ninedev-i commented on components/content/VideoGallery.vue
> +type Video = [string, string, string];
done

2024-10-25 15:00 UTC, ninedev-i commented on pages/contents/video.vue
> +      <template v-for="(category, i) in flattenCategories(videoCategories, locale)" :key="category.name">
немного зарефакторил

2024-10-25 15:01 UTC, ninedev-i commented on pages/contents/video.vue
> +        <template v-if="data!.filter((item) => item.category === category.name).length">
оптимизировал через мемоизацию в computed

2024-10-28 09:45 UTC, KraPete approved these changes

2024-10-29 12:33 UTC, merged