Feature/product page
wirenboard/website pull request #83
Opened 2024-11-25 14:11 UTC by ninedev-i

Добавил страницу товара
![image](https://github.com/user-attachments/assets/b61f9ad8-7e8c-413d-8269-9919faba1417)

2024-11-26 05:06 UTC, ninedev-i commented on utils/toTriads.ts
> +};
useless

2024-11-26 05:06 UTC, ninedev-i commented on composables/useApi.ts
> +export const useApi: typeof useFetch = (url: string, opts?) => {
useless

2024-11-26 05:06 UTC, ninedev-i commented on composables/useApi.ts
> +}
useless

2024-11-26 05:07 UTC, ninedev-i commented on components/content/ProductOptions.vue
> +      <div v-html="option.description" class="product-optionDescription"></div>
useless

2024-11-26 05:07 UTC, ninedev-i commented on content/ru/_catalog/controllers/wiren-board-8.md
> +![](img/catalog/controllers/wiren-board-8/wide.png)
useless

2024-11-26 05:07 UTC, ninedev-i commented on components/content/Product.vue
> +    "scheduled": "ожидается через 2—3"
useless

2024-11-26 05:09 UTC, ninedev-i commented on content/ru/_catalog/controllers/wiren-board-8.md
> +type: Контроллер для автоматизаци
useless

2024-11-26 05:10 UTC, ninedev-i commented on pages/contents/product/[slug].vue
> +  title: `${data.value.type} ${data.value.name}`,
useless

2024-11-26 05:10 UTC, ninedev-i commented on composables/useApi.ts
> +    : {};
useless

2024-11-26 05:16 UTC, ninedev-i commented on components/content/Product.vue
> +        </swiper-slide>
useless

2024-11-26 05:17 UTC, ninedev-i commented on components/content/Product.vue
> +const product: any = await useApi<Product>(`/product/${data.value.article}/?locale=${locale.value}`);
useless

2024-11-26 05:17 UTC, ninedev-i commented on components/content/Product.vue
> +const product: any = await useApi<Product>(`/product/${data.value.article}/?locale=${locale.value}`);
useless

2024-11-26 05:35 UTC, ninedev-i commented on components/content/ProductOptions.vue
> +}
useless

2024-11-26 05:35 UTC, ninedev-i commented on common/types.ts
> +}
useless

2024-11-26 05:40 UTC, ninedev-i commented on components/content/ProductOptions.vue
> +      <NuxtImg class="product-optionImage" :src="`https://wirenboard.com/storage/cache/${option.image}`" />
useless

2024-11-26 05:41 UTC, ninedev-i commented on components/content/ProductSolutions.vue
> +  .find());
useless

2024-11-26 05:41 UTC, ninedev-i commented on components/content/ProductSolutions.vue
> +  </section>
useless

2024-11-26 05:42 UTC, ninedev-i commented on nuxt.config.ts
> +  },
useless

2024-11-26 05:44 UTC, ninedev-i commented on components/content/ProductSolutions.vue
> +</script>
useless

2024-11-26 06:13 UTC, ninedev-i commented on common/types.ts
> +  price_max?: number;
it is right in our case

2024-11-26 06:14 UTC, ninedev-i commented on components/content/ProductSolutions.vue
> +</i18n>
fixed

2024-11-28 07:23 UTC, aadegtyarev commented
**1. Начало страницы товара**

Огромное пустое место под названием с картинкой ставит в тупик. На низких экранах оно, наверное, выглядит хорошо, но на высоких кажется, что страница не прогрузилась.

![image](https://github.com/user-attachments/assets/b0f8cce7-9d13-4565-90c4-5423ad8babf5)
![image](https://github.com/user-attachments/assets/048594e8-20f9-4901-8348-5910c319484d)
![image](https://github.com/user-attachments/assets/f77147f2-65de-4d1e-9954-5fa88265476f)

2024-11-28 07:37 UTC, aadegtyarev commented
**3. Объявление видео и картинок**

Сейчас оно объявляется так:
```
images:
  - 1.webp
  - 2.jpg
  - 3.jpg
  - 4.jpg
  - 5.jpg
  - 6.jpg
  - 7.jpg
  - 8.jpg
  - 9.jpg
  - 10.jpg
  - 11.jpg
video:
  - https://peertube.wirenboard.com/videos/embed/0a424378-a514-446c-bfc7-6e9b7393080c
  - https://peertube.wirenboard.com/videos/embed/68c5da1d-17fc-41f6-82b9-9a591f3e4cc2
  - https://peertube.wirenboard.com/videos/embed/629d95d8-7ce8-4bad-83ad-7718ececeb9
```
С одной стороны удобно - меньше кода. С другой — ломает привычки в других разделах сайта, а ещё делает невозможным, например, сделать вместо встраиваемых роликов, обложки при клике на которые будет открываться страница с роликом. 

Предлагаю унифицировать.

2024-11-28 07:43 UTC, aadegtyarev commented
**4. Примеры использования**

Сейчас объявляются так и это очень похоже с тем, как было на сайте, то есть надо указать именно кейс:
```
use_cases:
  - liten_magnit
  - techsensor_module_cafe
  - rekota_hotel_vertical
```

Это хорошее решение, но в старом варианте была ещё ссылка на страницу внедрений, чтобы пользователи могли почитать и другие примеры, да и вообще о них узнали. Предлагаю добавлять автоматом эту ссылку на список внедрений. Можно где-то в настройках сайта задавать такие штуки.

![image](https://github.com/user-attachments/assets/cc44debd-14d7-4524-b135-3fbcdd72d4c3)

2024-11-28 07:45 UTC, aadegtyarev commented
5. Видео и ссылка на наш видеохостинг

![image](https://github.com/user-attachments/assets/9121561d-536c-42a5-a088-976edec61cfc)

Мне кажется, что в этом блоке уместно будет подставлять ссылку на наш perrtube, притом хочется не на весь perrtube, а на конкретный плейлист. Что думаешь? Конечно, это хорошо бы сделать один раз где-то в настройках и вставлять автоматом.

2024-11-28 07:50 UTC, aadegtyarev commented
**6. Опции**

![image](https://github.com/user-attachments/assets/572cf757-5ef0-4e62-81f7-e8fdc97e97b8)

С одной стороны классно, что мы из вынесли на страницу и теперь их не пропустят. С другой, мне не очень понятен кейс их применений. Если сказать пользователю, что такие опции есть, то вроде ок, полезно. Но вот по клику оно открывает калькулятор и… всё, сделать там мы уже ничего не можем, только добавить датчик в корзину без опций. Странно тут.

![image](https://github.com/user-attachments/assets/4a096a79-6864-4fb9-810c-ab07b7a9c5cd)

Предлагаю не пытаться дублировать функцию кнопки Опции под ценой и просто вывести карточки опций без клика по ним.

2024-11-28 07:54 UTC, aadegtyarev commented
**7. Комплектация**
Тут я не понял, а чем оно отличается от опций? Ну кроме того, что тут не все опции, а только кусочек. Например, датчик качества воздуха есть и в опциях и в комплектации, а других почему-то нет.

Предлагаю подумать, а нужно ли это вообще указывать.

![image](https://github.com/user-attachments/assets/539ee348-929e-47ea-9f09-0bd167421cda)

2024-11-28 08:01 UTC, aadegtyarev commented
**8. Порядок блоков на странице товаров**

Порядок блоков немного сбивает с толку, а так как страница длинная, то есть риск, что пользователи до конца никогда не долистают. Не знаю, хорошо это или плохо.

Может компромиссное решение? Например, можно сворачивать аккордионом опции, фото? Они занимают много места, но вроде как не очень нужно каждый раз показывать.

В целом я бы ожидал такой порядок на странице:
1. Блок с ценой и кратким описанием
2. Примеры внедрений.
3. Видео
4. Основные характеристики
5. Фоточки
6. Опции/комплектация

Если сворачивать фоточки и опции/комплектацию в аккордион, то так:
1. Блок с ценой и кратким описанием
2. Примеры внедрений.
3. Видео
4. Фоточки <свернуто>
5. Опции/комплектация <свернуто>
6. Основные характеристики

Наверное, даже хотелось бы где-то в настройках сайта задавать порядок блоков для всех товаров в одном месте. Очевидно, что он будет везде одинковый. Просто, чтобы можно было самому подвигать туда/сюда, чтобы добиться лучшего результата.

2024-11-28 08:30 UTC, aadegtyarev reviewed
Оставил комменты

2024-11-28 12:11 UTC, ninedev-i commented on components/content/Product.vue
> +        <div class="product-note">{{ t('retailPrice') }} <span v-if="product?.price_max">{{ t('from') }} {{ toTriads(product.price) }} {{ t('to') }} {{ toTriads(product.price_max) }} ₽ {{ t('dependsO
useless. nuxt do it automatically

2024-12-03 04:32 UTC, KraPete requested changes
`Контроллер для автоматизаци` буковку забыл в конце

2024-12-03 10:20 UTC, ninedev-i commented on components/content/Product.vue
> +const product = await useApi<Product>(`/product/${data.value.article}/?locale=${locale.value}`);
useless

2024-12-03 10:20 UTC, ninedev-i commented on content/ru/_catalog/sensors/wb-msw-v4.md
> +]
useless

2024-12-03 10:21 UTC, ninedev-i commented on content/ru/_catalog/sensors/wb-msw-v4.md
> +::
useless

2024-12-04 07:46 UTC, ninedev-i commented on content/ru/_catalog/controllers/wiren-board-8.md
> +]
useless

2024-12-19 06:07 UTC, merged